2020-01-05 16:50:49,964 DEBUG    root            Loaded Command Group: [u'gcloud', u'app']
2020-01-05 16:50:49,998 DEBUG    root            Loaded Command Group: [u'gcloud', u'app', u'create']
2020-01-05 16:50:49,999 DEBUG    root            Running [gcloud.app.create] with arguments: []
2020-01-05 16:50:50,004 DEBUG    root            (gcloud.app.create) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials, or if you have already logged in with a
different account:

  $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
Traceback (most recent call last):
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 984, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 798, in Run
    resources = command_instance.Run(args)
  File "/opt/google-cloud-sdk/lib/surface/app/create.py", line 59, in Run
    api_client = appengine_api_client.GetApiClientForTrack(self.ReleaseTrack())
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/appengine_api_client.py", line 58, in GetApiClientForTrack
    return AppengineApiClient.GetApiClient(api_version)
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/api/appengine_api_client_base.py", line 64, in GetApiClient
    return cls(core_apis.GetClientInstance('appengine', api_version))
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/apis.py", line 320, in GetClientInstance
    check_response_func=CheckResponseForApiEnablement())
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/apis_internal.py", line 157, in _GetClientInstance
    http_client = http_creds.Http(response_encoding=http_creds.ENCODING)
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/core/credentials/http.py", line 81, in Http
    allow_account_impersonation=allow_account_impersonation)
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 318, in LoadIfEnabled
    return Load(allow_account_impersonation=allow_account_impersonation)
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 363, in Load
    cred = _Load(account, scopes, prevent_refresh)
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 416, in _Load
    raise NoActiveAccountException()
NoActiveAccountException: You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials, or if you have already logged in with a
different account:

  $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
2020-01-05 16:50:50,004 ERROR    root            (gcloud.app.create) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials, or if you have already logged in with a
different account:

  $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
